export const TEST_LIST_REAQUEST = "TEST_LIST_REAQUEST";
export const TEST_LIST_SUCCESS = "TEST_LIST_SUCCESS";
export const TEST_LIST_FAIL = "TEST_LIST_FAIL";

export const TEST_CREATE_REAQUEST = "TEST_CREATE_REAQUEST";
export const TEST_CREATE_SUCCESS = "TEST_CREATE_SUCCESS";
export const TEST_CREATE_FAIL = "TEST_CREATE_FAIL";

export const TEST_UPDATE_REAQUEST = "TEST_UPDATE_REAQUEST";
export const TEST_UPDATE_SUCCESS = "TEST_UPDATE_SUCCESS";
export const TEST_UPDATE_FAIL = "TEST_UPDATE_FAIL";

export const TEST_DELETE_REAQUEST = "TEST_DELETE_REAQUEST";
export const TEST_DELETE_SUCCESS = "TEST_DELETE_SUCCESS";
export const TEST_DELETE_FAIL = "TEST_DELETE_FAIL";